# Generated by Django 4.1.7 on 2023-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_price_rrc_remove_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
