# Generated by Django 4.1.7 on 2023-03-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_basket_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
